---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: docs/.vitepress
  label: Theme
  create: all
  match: "**/*"
- type: document
  path: docs/.vitepress/config.js
  label: Config
  match: "**/*"
- type: directory
  path: ''
  label: Pages
  create: all
  match: "**/*"
upload_dir: docs/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
